function modelNames = GetModelNames
    modelNames = { ...
    'Alfentanil-Model-2.2', ...
    'Alprazolam-Model-1.1', ...
    'Amikacin-Model-1.2', ...
    'Atazanavir-Model-1.2', ...
    'Carbamazepine-Model-1.2', ...
    'Cimetidine-Model-1.1', ...
    'Clarithromycin-Model-1.2', ...
    'Dapagliflozin-Model-1.3', ...
    'Efavirenz-Model-1.1', ...
    'Erythromycin-Model-1.3', ...
    'Ethinylestradiol-Model-1.1', ...
    'Felodipine-Model-1.0', ...
    'Fluconazole-Model-1.0', ...
    'Fluvoxamine-Model-1.2', ...
    'Itraconazole-Model-1.3', ...
    'Mefenamic-acid-Model-1.2', ...
    'Mexiletine-Model-1.1', ...
    'Midazolam-Model-1.1', ...
    'Moclobemide-Model-1.1', ...
    'Montelukast-Model-1.2', ...
    'Omeprazole-Model-1.1', ...
    'Raltegravir-Model-1.2', ...
    'Rifampicin-Model-1.2', ...
    'S-Mephenytoin-Model-1.1', ...
    'Sildenafil-Model-1.0', ...
    'Sufentanil-Model-1.2', ...
    'Tizanidine-Model-1.1', ...
    'Triazolam-Model-1.1', ...
    'Vancomycin-Model-1.2', ...
    'Verapamil-Model-1.2' ...
    };